### ISSUE TITLE
Add regeneration speed

### ISSUE THREAD

**Issue by BornToDoStuff** [MicleBrick/ExplosionRegen#47]
A quality of life improvement would be to add a regeneration speed parameter. It is not needed for functionality, but currently there is only really a "delay" parameter, and it would be nice to have both a delay and speed parameter (ex: wait 30 seconds, then over 30 seconds place blocks back).

**Comment by MicleBrick** [comment]
For limiting regeneration for performance, use `placement_intensity`. For controlling how fast it regenerates the explosion, use `distance_delay` and `distance_delay_cap`. From `config.yml`:
```YAML
# Time in minutes after exploding blocks should regenerate
regen_delay: 1.0

# Time in seconds of additional delay for each block away (taxicab distance)
distance_delay: 2.0

# Maximum distance from center of explosion to keep adding time for
# Also used for things the distance of which can't be calculated, such as entities
distance_delay_cap: 6

# Maximum time in milliseconds that can be spent per tick placing blocks. (50 milliseconds per tick).
# Setting this higher will result in lag spikes
placement_intensity: 5
```
